### ISSUE TITLE
Pull request to the original repo

### ISSUE THREAD

**Issue by Moustachauve** [jayluxferro/Cookie-Editor#1]
Hello! I'm glad you ported my extension to safari! 

I'd be really happy if you were willing do create a pull request to my repo so that I could share your work so that anyone using Cookie-Editor could benefit from your help!

Thanks for considering it.

**Comment by Moustachauve** [comment]
Closing since Cookie-Editor supports safari natively now

**Comment by jayluxferro** [comment]
Thanks @Moustachauve . Sorry I just saw the PR request. Thanks a lot for making it available on Safari.
